# yaml-language-server: $schema=https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
---
version: "3"

services:
  runner:
    image: drone/drone-runner-docker:1
    container_name: runner
    restart: always
    env_file: .env
    ports:
      - 3000:3000
