---
kind: pipeline
type: docker
name: lint

steps:
  - name: validate
    image: hashicorp/terraform
    environment:
      TF_IN_AUTOMATION: 1
    commands:
      - terraform init -backend=false -input=false
      - terraform validate

  - name: tflint
    image: terraform-linters/tflint-bundle
    commands:
      - tflint
