---
kind: pipeline
type: docker
name: lint

steps:
  - name: validate
    image: hashicorp/terraform
    commands:
      - terraform validate

  - name: tflint
    image: terraform-linters/tflint-bundle
    commands:
      - tflint
