#cloud-config
# yaml-language-server: $schema=https://raw.githubusercontent.com/canonical/cloud-init/main/cloudinit/config/schemas/versions.schema.cloud-config.json
---
apt:
  preserve_sources_list: true
  sources:
    tailscale:
      source: "deb https://pkgs.tailscale.com/stable/debian bullseye main"
      key: ${tailscale_apt_key}
    docker:
      source: "deb https://download.docker.com/linux/debian bullseye stable"
      key: ${docker_apt_key}

package_update: true
package_upgrade: true
package_reboot_if_required: true
packages:
  - zsh
  - htop
  - git
  - tailscale
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-compose-plugin

disk_setup:
  /dev/sda:
    table_type: gpt
    layout: true
    overwrite: false

fs_setup:
  - label: gitea
    filesystem: ext4
    partition: auto
    device: /dev/sda
    overwrite: false

mounts:
  - ["/dev/sda", "/mnt", "ext4", "defaults", "0", "0"]

write_files:
  - path: /root/gitea-compose.yaml
    encoding: b64
    owner: root:root
    permissions: "0o644"
    content: ${gitea_compose}
  - path: /root/Caddyfile
    encoding: b64
    owner: root:root
    permissions: "0o644"
    content: ${caddyfile}
  - path: /var/run/cloud-tmp/ssh-shim
    encoding: b64
    content: ${ssh_shim}

groups:
  - docker

users:
  - default
  - name: git
    groups: docker
    shell: /home/git/ssh-shim
    uid: 1000

runcmd:
  - ["sudo", "mv", "/var/run/cloud-tmp/ssh-shim", "/home/git"]
  - ["sudo", "chmod", "+x", "/home/git/ssh-shim"]
  - ["sudo", "chown", "git:git", "/home/git/ssh-shim"]
  - ["sudo", "mkdir", "-p", "/mnt/data/pg", "/mnt/data/git", "/mnt/data/caddy"]
  - ["sudo", "tailscale", "up", "--authkey", "${tailscale_key}"]
  - ["sudo", "docker", "compose", "-f", "/root/gitea-compose.yaml", "up", "-d"]
